version: "3"

services:
  app:
    container_name: ${APP_NAME}
    image: ${APP_NAME}/${APP_NAME}:${APP_VERSION}
    restart: unless-stopped
    ports:
      - ${MAPPING_PORT}:${APP_PORT}
    volumes:
      - "${LOG_PATH}logs:/logs"
      - "${CONFIG_PATH}:/config"
    environment:
      TZ: Asia/Shanghai